### ISSUE TITLE
Change Wordpress deploy extraction

### ISSUE THREAD

**Issue by jonathandietz** [automationforamerica/ansible-wordpress#3]
Wordpress shouldn't be extracted into the nginx site directory. We should be extracting it somewhere else and then symlinking do that directory once all of the files are extracted.

Example

/releases/[yyyymmdd-hhmm]/<the files>
/releases/20150612-0212/<the files>
/current -> /releases/20150612-0212/

**Comment by automationforamerica** [comment]
Addressing in the `capistrano-esque-deploys` branch, but using the SHA1-sum of the tarball for versioning instead of a timestamp.

**Comment by automationforamerica** [comment]
Resolved
